import json, re, shutil, struct, subprocess, sys, zlib
from pathlib import Path

HOME = Path('/home/blots')
# Apps are optional image layers; list only the ones installed in this image.
APPS = {key: app for key, app in json.loads(Path('/opt/blots/apps.json').read_text()).items() if not app['command'] or shutil.which(app['command'][0])}

def appearance():
    return json.loads((HOME / 'appearance.json').read_text())

def rgb(color):
    if not re.fullmatch(r'#[0-9a-fA-F]{6}', color):
        raise ValueError('Invalid desktop color')
    return tuple(int(color[i:i+2], 16) for i in (1, 3, 5))

def wallpaper(color):
    base = rgb(color)
    rows = bytearray()
    for y in range(960):
        rows.append(0)
        for x in range(1280):
            light = .26 * (1 - y / 960) + .32 * max(0, 1 - ((x / 600)**2 + ((y - 660) / 430)**2))
            shade = .12 * (y / 960) * (x / 1280)
            rows.extend(round(c * (1 - light - shade) + 255 * light) for c in base)
    def chunk(kind, data):
        return struct.pack('!I', len(data)) + kind + data + struct.pack('!I', zlib.crc32(kind + data))
    png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('!2I5B', 1280, 960, 8, 2, 0, 0, 0)) + chunk(b'IDAT', zlib.compress(rows)) + chunk(b'IEND', b'')
    file = HOME / 'desktop.png'
    file.with_suffix('.tmp').write_bytes(png)
    file.with_suffix('.tmp').replace(file)

def prepare():
    from cursor import theme
    theme(HOME, appearance())
    color = appearance()['color']
    wallpaper(color)
    r, g, b = (round(c * .5 + 127.5) for c in rgb(color))
    argb = 0xff000000 | (r << 16) | (g << 8) | b
    # Older builds kept a browser profile per extra desktop; reclaim that disk.
    for screen in range(2, 5):
        shutil.rmtree(HOME / 'profiles' / f's{screen}', ignore_errors=True)
    profile = HOME / 'profiles' / 's1'
    for name in ('SingletonLock', 'SingletonCookie', 'SingletonSocket'):
        (profile / name).unlink(missing_ok=True)
    Path('/tmp/.X1-lock').unlink(missing_ok=True)
    Path('/tmp/.X11-unix/X1').unlink(missing_ok=True)
    default = profile / 'Default'
    default.mkdir(parents=True, exist_ok=True)
    file = default / 'Preferences'
    settings = json.loads(file.read_text()) if file.exists() else {}
    browser = settings.setdefault('browser', {})
    browser['custom_chrome_frame'] = True
    browser['window_placement'] = dict(left=80, top=80, right=1200, bottom=872, maximized=False, work_area_left=0, work_area_top=0, work_area_right=1280, work_area_bottom=960)
    browser.setdefault('theme', {})['color_scheme2'] = 1
    settings.setdefault('extensions', {}).setdefault('theme', {}).update(id='autogenerated_theme_id', system_theme=0)
    settings.setdefault('autogenerated', {}).setdefault('theme', {})['color'] = argb - 2**32
    file.write_text(json.dumps(settings))

def dock(screen):
    import gi
    import cairo, math
    gi.require_version('Gtk', '3.0')
    gi.require_foreign('cairo')
    from gi.repository import Gtk, Gdk, GLib
    from urllib.request import Request, urlopen
    window = Gtk.Window(type=Gtk.WindowType.TOPLEVEL)
    window.set_title('Blots dock')
    window.set_decorated(False)
    window.set_resizable(False)
    window.set_type_hint(Gdk.WindowTypeHint.DOCK)
    window.set_skip_taskbar_hint(True)
    window.set_keep_above(True)
    window.set_name('blots-dock')
    window.set_default_size(194, 68)
    def round_corners(widget, allocation):
        if not widget.get_realized():
            return
        w, h, radius = allocation.width, allocation.height, 16
        surface = cairo.ImageSurface(cairo.FORMAT_A8, w, h)
        pen = cairo.Context(surface)
        for x, y, angle in ((w-radius, radius, -math.pi/2), (w-radius, h-radius, 0), (radius, h-radius, math.pi/2), (radius, radius, math.pi)):
            pen.arc(x, y, radius, angle, angle + math.pi/2)
        pen.close_path(); pen.fill()
        widget.get_window().shape_combine_region(Gdk.cairo_region_create_from_surface(surface), 0, 0)
    window.connect('size-allocate', round_corners)
    box = Gtk.Box(spacing=4)
    box.set_halign(Gtk.Align.CENTER)
    window.add(box)
    for app in ('browser', 'terminal', 'files'):
        button = Gtk.Button()
        button.set_tooltip_text(APPS[app]['name'])
        button.set_image(Gtk.Image.new_from_icon_name(APPS[app]['icon'], Gtk.IconSize.DIALOG))
        button.connect('clicked', lambda _button, app=app: urlopen(Request('http://127.0.0.1:8766/launch', data=json.dumps(dict(app=app, screen=screen)).encode(), headers={'Content-Type': 'application/json'}), timeout=5).close())
        box.pack_start(button, False, False, 0)
    css = Gtk.CssProvider()
    Gtk.StyleContext.add_provider_for_screen(Gdk.Screen.get_default(), css, Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION)
    last_color, last_wallpaper = None, None
    def update():
        nonlocal last_color, last_wallpaper
        color = appearance()['color']
        if color != last_color:
            if screen == 1:
                wallpaper(color)
            r, g, b = rgb(color)
            css.load_from_data(f'#blots-dock {{background:rgb({round(r*.8+51)},{round(g*.8+51)},{round(b*.8+51)});border:1px solid rgba(255,255,255,.5);border-radius:16px;padding:8px;}} #blots-dock button {{background:transparent;border:0;box-shadow:none;padding:0;min-width:48px;min-height:48px;}} #blots-dock button:hover {{background:rgba(255,255,255,.2);}}'.encode())
            last_color = color
        modified = (HOME / 'desktop.png').stat().st_mtime_ns
        if modified != last_wallpaper:
            subprocess.run(['feh', '--bg-fill', str(HOME / 'desktop.png')], check=True)
            last_wallpaper = modified
        return True
    update()
    window.show_all()
    round_corners(window, window.get_allocation())
    window.move(543, 884)
    GLib.timeout_add_seconds(2, update)
    Gtk.main()

if __name__ == '__main__':
    if sys.argv[1] == '--prepare':
        prepare()
    else:
        dock(int(sys.argv[1]))
